  <!-- Footer-->
<footer>
<div class="header-footer">
  <img src="/unima-gaming/public/assets/front/img/unima-white.png" width="300" height="300" label="logo footer unima blanc">
<div class="icons">
  <i class="fab fa-twitter" style="color: #ffffff;"></i>
  <i class="fab fa-instagram" style="color: #ffffff;"></i>
  <i class="fab fa-tiktok" style="color: #ffffff;"></i>
  <i class="fab fa-youtube" style="color: #ffffff;"></i>
</div>
</footer>
</body>
</html>