<div class="container-home">
    <div class="banner">
        <div class="title-home">
            <h1>RELEVE DES DEFIS SUR BRAWL STARS</h1>
        </div>
    </div>
 <div class="content">
    <div class="home1">
        <h2>Prêt à relever des défis palpitants et à gagner des récompenses exclusives dans Brawl Stars ?</h2>
        <p>Bienvenue sur les missions épiques de <span class="orange">Brawl Stars</span> ajoutées par <span class="orange">Unima Gaming</span>, 
        l'endroit où l'action ne s'arrête jamais ! 
        Plongez dans l'univers explosif de <span class="orange">Brawl Stars</span> en accomplissant des quêtes stimulantes et en récoltant des récompenses exceptionnelles. 
        Êtes-vous prêt à devenir un véritable Brawler ?</p>
    </div>
    <div class="bloc-bs">
        <div class="flex-bs">
            <h2>Section des quêtes :</h2>
        </div>    
        <div class="img-bs">
            <p><span class="orange">Explorez les Quêtes :</span> Découvrez une grande variété de quêtes, des défis tactiques aux missions d'élite. Chaque quête offre une expérience de jeu unique.</p>
            <img class="bs" width="300" height="230" src="/unima-gaming/public/assets/front/img/brawlstars.jpg" label="image brawl stars">
        </div>    
    </div>
    <div class="bloc-avantages">
        <h2>Avantages :</h2>
        <ul>
            <li>- Accomplissez des quêtes <span class="orange">variées</span> et <span class="orange">stimulantes</span>, adaptées à tous les styles de jeu.</li>
            <li>- Gagnez des <span class="orange">récompenses</span> exclusives, y compris des gemmes, des skins rares, des cartes cadeaux, des virements paypal et bien plus encore.</li>
            <li>- Relevez des défis en <span class="orange">solo</span> ou en <span class="orange">équipe</span> avec vos amis Brawlers.</li>
            <li>- Suivez votre progression à travers un tableau de bord personnalisé.</li>
            <li>- Relevez des défis en <span class="orange">solo</span> ou en <span class="orange">équipe</span> avec des amis.</li>
            <li>- Suivez votre progression dans le classement et montez dans le classement pour débloquer des <span class="orange">récompenses</span> plus impressionnantes.</li>
        </ul>
    </div>
    <div class="bloc-marche">
        <h2>Comment ça marche :</h2>
        <ul>
            <li>- Explorez la liste des <span class="orange">quêtes disponibles</span>.</li>
            <li>- Sélectionnez une <span class="orange">quête</span> qui vous intéresse.</li>
            <li>- Suivez les <span class="orange">instructions</span> et <span class="orange">relevez le défi</span>.</li>
        </ul>
    </div>
    <div class="bloc-validation">
        <h2>Validation des Missions :</h2>
        <p>Une fois que vous avez terminé les missions avec succès, rendez-vous dans la page Validation des Quêtes
           et soumettez une capture d'écran des missions réalisées pour les valider.</p>
    </div>
    <div class="end-home">
        <h2>C'est à Vous de Jouer !</h2>
        <p>Rejoignez-nous dès maintenant et devenez le numéro 1 ! 
           Mettez toutes les chances de votre côté pour devenir le plus riche et le plus respecté d'<span class="orange">Unima Gaming</span>. L'action commence ici !
        </p>
    </div>
 </div>
</div>