<div class="login-container">
    <div class="login-container-block">
        <img class="img-login" width="280" height="400" src="/unima-gaming/public/assets/front/img/unima-gaming.png" alt="image unima gaming pour connexion">
        <div class="login-form">
            <h1>Connexion</h1>
            <form class="user" action="#" method="post">
                <input type="email" name="email" class="email-form" id="exampleInputEmail" placeholder="Email">
                <input type="password" name="password" class="pass-form" id="exampleInputPassword" placeholder="Mot de passe">
                <input type="submit" name="loginForm" class="login-btn" value="se connecter">
            </form>
        </div>
    </div>
</div>