<div class="register-container">
    <div class="register-container-block">
        <img class="img-register" width="280" height="400" src="/unima-gaming/public/assets/front/img/unima-footer.png" alt="image unima gaming pour inscription">
        <div class="register-form">
            <h1>Inscription</h1>
            <form class="user-register" action="#" method="post">
                <input type="name" name="name" class="name-form" id="exampleInputName" placeholder="Nom">
                <input type="email" name="email" class="email-form" id="exampleInputEmail" placeholder="Email">
                <input type="password" name="password" class="pass-form" id="exampleInputPassword" placeholder="Mot de passe">
                <input type="submit" name="loginForm" class="register-btn" value="Register">
            </form>
        </div>
    </div>
</div>